#!/usr/bin/env python3 

import numpy as np
import imutils
import pyautogui as pag
from utils import *
import cv2

#assets_play_button          = cv2.imread("./assets/play-button.png");
# import game map assets, fight screen asset for detection

def mss_grab_screen():

    try:

        # focus on game
        pag.click(x=410+2200, y=550)
        while(true):

            image = grabscreenimage();
            #printscreen = np.array(image)
            #highlightinimage(image, 420, 275)
            printimage(image)
            cv2.imshow(window_name, cv2.cvtcolor(img, cv2.color_bgr2rgb))
            if (

    except exception as e:
        print('exiting... closing display', e)
        closeimagedisplay()

mss_grab_screen()
